apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: workspace
  name: workspace
  namespace: default
spec:
  selector:
    matchLabels:
      app: workspace-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: workspace-ui
    spec:
      containers:
        - image: gcr.io/zopsmart-176211/workspace-ui:20220301105132
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: 80
              scheme: HTTP
            successThreshold: 1
            timeoutSeconds: 1
          name: workspace-ui
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: workspace-ui
  labels:
    app: workspace-ui
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: workspace-ui
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: workspace-ui
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: workspace-ui
  targetCPUUtilizationPercentage: 80